export { default as BreadcrumbFn } from 'components/Breadcrumb';
export { default as Logo} from 'components/Logo';
export { default as PaginationFn} from 'components/Pagination';
export { default as ProductCard} from 'components/ProductCard';
export { default as ShippingInformation} from 'components/ShippingInformation';
export { default as PaymentInformation} from 'components/PaymentInformation';
export { default as ProductSuggestion} from 'components/ProductSuggestion';
export { default as OrderDetails} from 'components/OrderDetails';
export { default as BackToTop} from 'components/BackToTop';
export { default as HomeCarousel} from 'components/Carousel';
export { default as OrderConfirmed} from 'components/OrderConfirmed';
export { default as Modal} from 'components/Modal';
export {default as Login} from 'components/Login';
export {default as Register} from 'components/Register';
export { default as AddNewAddress} from 'components/AddNewAddress';
export { default as Address} from 'components/Address';
export { default as EditAddress} from 'components/EditAddress';